### ISSUE TITLE
When a post is checked for spam after being edited, include that fact in the Akismet API request

### ISSUE THREAD

**Issue by cfinke** [akhoury/nodebb-plugin-spam-be-gone#101]
Currently, edited posts are checked for spam after being edited, but they don't include the recheck_reason parameter as documented at https://akismet.com/development/api/#comment-check

Including `recheck_reason=edit` will prevent false positives, as it won't see the re-checked content as a duplicate or near-duplicate copy of the original post.

**Comment by barisusakli** [comment]
@cfinke thanks for reporting published new versions
v1.0.3 (nbb 2.x)
v2.0.6 (nbb 3.x)
