### ISSUE TITLE
nodebb v3.x - can't save any spam-be-gone settings

### ISSUE THREAD

**Issue by ryanfantus** [akhoury/nodebb-plugin-spam-be-gone#102]
Hello,

I just installed nodebb v3 and enabled the spam-be-gone plugin. After rebuilding and restarting, when I try to configure the plugin, I'm unable so save anything in the plugin. No API keys, etc., the save button doesn't seem to do anything.

I'm sure you can imagine this is rather important for me :)

Thanks for contributing to such an awesome software!

**Comment by barisusakli** [comment]
@ryanfantus thanks for reporting, I will take a look

**Comment by dinhitcom** [comment]
I have the same issue, I always get the empty field alert without an empty field
