### ISSUE TITLE
Match NodeBB Language (RE Captcha)

### ISSUE THREAD

**Issue by justinlosh** [akhoury/nodebb-plugin-spam-be-gone#29]
Is it possible to have the language match that of what is set for the NodeBB instance? For example, the language on my instance is set to en_US, but I am in Korea. So the text on the RE Captcha automatically defaults to kr_KR (Korean).

**Comment by akhoury** [comment]
yes, there is. Will add this soon

**Comment by huegelc** [comment]
How soon :) :+1:

**Comment by akhoury** [comment]
there you go. You need to use nodebb-plugin-spam-be-gone@0.4.7

**Comment by huegelc** [comment]
What are this warnings about
```
npm WARN unmet dependency /var/www/nodebb/node_modules/lwip requires async@'~0.9.0' but will load
npm WARN unmet dependency /var/www/nodebb/node_modules/async,
npm WARN unmet dependency which is version 1.5.2
npm WARN unmet dependency /var/www/nodebb/node_modules/redisearch requires async@'~0.9.0' but will load
npm WARN unmet dependency /var/www/nodebb/node_modules/async,
npm WARN unmet dependency which is version 1.5.2
nodebb-plugin-spam-be-gone@0.4.7 node_modules/nodebb-plugin-spam-be-gone
├── project-honeypot@0.0.0
├── akismet@1.0.0
└── simple-recaptcha@1.0.0
```

**Comment by akhoury** [comment]
seems like you have the `async` module newer than expected.. dont think this is a big deal, but you can try to re-install all the modules fresh.

**Comment by huegelc** [comment]
yes, nodebb seems to start after editing package.json

**Comment by akhoury** [comment]
well, technically you should wait for the release of NodeBB with that package.json changed, but that works for now
