### ISSUE TITLE
captcha on the login page

### ISSUE THREAD

**Issue by akhoury** [akhoury/nodebb-plugin-spam-be-gone#32]
https://github.com/NodeBB/NodeBB/issues/3276

**Comment by AdamAzote** [comment]
Hi @akhoury are you able to do this feature ? I think it's super useful to avoid bruteforce.

**Comment by akhoury** [comment]
@AdamAzote which theme are you using? just so i can make sure i target that as well

**Comment by theAkito** [comment]
@akhoury 

I am using [this theme](https://github.com/NodeBB/nodebb-theme-lavender) and the reCAPTCHA works on registration page, but is completely invisible on the login page. Yet, when I try to log in, it fails because I did not solve the invisible reCAPTCHA.

**Comment by barisusakli** [comment]
This should work now I think 
![image](https://user-images.githubusercontent.com/2583394/223573159-0ee408f1-05c5-42fa-8a87-749a10d10801.png)
