### ISSUE TITLE
User ID not reported when a message is marked as spam

### ISSUE THREAD

**Issue by milipili** [akhoury/nodebb-plugin-spam-be-gone#33]
When you have the following:
```
by uid: undefined@121.150.198.231 was flagged as spam and rejected
```

It would be nice to have the real user id who tried to create the topic.

**Comment by barisusakli** [comment]
I fixed it in the above PR, those hooks werent passed the username just the user id

**Comment by milipili** [comment]
By the way, here is a discussion on NodeBB : https://github.com/NodeBB/NodeBB/issues/3437.
Since the Notepad++ Community has a lot of spam, this plugin is just absolutely necessary :)
