### ISSUE TITLE
How long until it shows?

### ISSUE THREAD

**Issue by Fastidious** [akhoury/nodebb-plugin-spam-be-gone#38]
How long until  updates show up on the panel?

**Comment by julianlam** [comment]
Updates?

**Comment by julianlam** [comment]
New versions of this plugin should show up hourly.

**Comment by Fastidious** [comment]
@julianlam odd, its been more than three hours, and I am still at 0.41, nothing new showing. It is 0.42 now, correct?

**Comment by julianlam** [comment]
Depends on your version of NodeBB. For v0.8.0, v0.4.2 is recommended by nbbpm now.
