### ISSUE TITLE
Does it work with 0.8.2 forum?

### ISSUE THREAD

**Issue by NicolasSiver** [akhoury/nodebb-plugin-spam-be-gone#39]
I have activate only re-captcha, but it doesn't work. After check of errors on page, I can find this:

```
window.plugin = window.plugin || &#123;&#125;;
			plugin["spam-be-gone"] = window.plugin["spam-be-gone"] || &#123;&#125;;
			plugin["spam-be-gone"].recaptchaArgs = &#123
```

**Comment by akhoury** [comment]
i wonder is something is parsing that raw `html` value - https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/a246b4deb699b3df631558376e6067b719fab186/library.js#L107-L114 

Ill test it out, sorry for the delay

**Comment by akhoury** [comment]
@psychobunny could the template be escaping the curly brackets?
https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/register.tpl#L64
```
		<!-- BEGIN regFormEntry -->
				<div class="form-group">
					<label for="register-{regFormEntry.styleName}" class="col-lg-4 control-label">{regFormEntry.label}</label>
					<div id="register-{regFormEntry.styleName}" class="col-lg-8">
						{{regFormEntry.html}}
					</div>
				</div>
				<!-- END regFormEntry -->
```

**Comment by NicolasSiver** [comment]
Yes, it could be. 
I did total overhaul of my theme. And re-captcha renders Ok now in register form.
