### ISSUE TITLE
Add stopforumspam

### ISSUE THREAD

**Issue by henrikekblad** [akhoury/nodebb-plugin-spam-be-gone#40]
Hi, thanks for a great plugin.

Noticed a lot of new spam accounts lately. Their IP is in the stopforumspam.com database. 
Might be if you can add support for their api on a rainy day.
https://www.stopforumspam.com

**Comment by akhoury** [comment]
@henrikekblad I [did try](https://github.com/NodeBB/NodeBB/issues/1213#issuecomment-37617591) stopforumspam.com when i initially started writing this plugin, but it wasn't that great. 

I guess I can just re-add it for the ones who would prefer using it.

**Comment by henrikekblad** [comment]
Yep, guess it would be best to check both places if possible.

Damn spammers.. Get a life.

**Comment by mtaki14** [comment]
Any news regarding this? On our forum we get quite a few spammers that get through but upon checking they are known in the stopforumspam database

**Comment by julianlam** [comment]
Why, yes, it looks like [this plugin has supported StopForumSpam since Jan 2019 :smile: ](https://github.com/akhoury/nodebb-plugin-spam-be-gone/pull/66)

**Comment by mtaki14** [comment]
To my understanding the implementation allows for directly reporting users to the stopforumspam database. But can it also be used to prevent known spammers from sfs from registering?

**Comment by tuicemen** [comment]
> @julianlam To my understanding the implementation allows for directly reporting users to the stopforumspam database. But can it also be used to prevent known sfs spammers from getting through?
I noticed this **Can't prevent known sfs spammers from getting through!** . Also the option to report does no good if the IP is already in the stopforumspam blacklisted  user database.
Please allow option to check users against that data base before hand.
 Our forum currently can't stop spammers based off that data base. 
Support for StopForumSpam is currently majorly flawed.
