### ISSUE TITLE
broken in newer nodebb 0.9.x/0.8.x

### ISSUE THREAD

**Issue by nwgat** [akhoury/nodebb-plugin-spam-be-gone#41]
it does not work in newer nodebb :(
shows up in plugins but its missing on register page

**Comment by akhoury** [comment]
do you have a public link to your registration page?

**Comment by nwgat** [comment]
for some reason it seems to work now
http://forum.nwgat.ninja/register

**Comment by julianlam** [comment]
Glad to hear it :smile:
