### ISSUE TITLE
"Topic Rename" spam

### ISSUE THREAD

**Issue by herf** [akhoury/nodebb-plugin-spam-be-gone#46]
Have observed users on our site (over the past few days) creating non-spam topics, then renaming them to spam titles.

These seem to be getting through (maybe even 100% of the time?) Is there a way to hook "topic rename" and run it through spam-be-gone?

**Comment by akhoury** [comment]
Yes. Good idea

**Comment by herf** [comment]
For a test, I commented out editing the title in src/posts/edit.js - will see if this is enough of a deterrent to make the spam go away.

**Comment by barisusakli** [comment]
Do I have npm publish rights?

**Comment by akhoury** [comment]
@barisusakli Yes, you should, https://www.npmjs.com/package/nodebb-plugin-spam-be-gone/access

but anyways, i just published 0.4.7 because of issue#29

**Comment by akhoury** [comment]
you might wanna up the version required in `NodeBB/package.json`
