### ISSUE TITLE
NodeBB 1.1.1 "unsaved-changes" popup

### ISSUE THREAD

**Issue by KitsuneSolar** [akhoury/nodebb-plugin-spam-be-gone#49]
Open spam-be-gone page settings. Not changes setting, go any another page - show popup:

![screenshot-2016-08-09-02-27-49](https://cloud.githubusercontent.com/assets/12877339/17499959/faccd7aa-5dd9-11e6-8144-8a8f6ad2eb78.png)

**Comment by julianlam** [comment]
Hm, that's interesting. @akhoury, the "unsaved changes" popup happens if a particular element has executed the `change` event. Perhaps that's what's happening in your plugin?
