### ISSUE TITLE
[NodeBB 1.1.2] "Unsaved changes" popup

### ISSUE THREAD

**Issue by KitsuneSolar** [akhoury/nodebb-plugin-spam-be-gone#50]
https://github.com/akhoury/nodebb-plugin-spam-be-gone/issues/49

Hi! :) Error. I did **not change any settings**, but still error is displayed.
But now the normal text.

![screenshot-2016-08-11-01-23-58](https://cloud.githubusercontent.com/assets/12877339/17573326/5a7df696-5f62-11e6-8ef4-7c4a66d2ed29.png)

- NodeBB v1.1.2
- spam-be-gone v0.4.9

**Comment by akhoury** [comment]
it needs `spam-be-gone@v0.4.10`
