### ISSUE TITLE
Captcha not showing up

### ISSUE THREAD

**Issue by Rantahu** [akhoury/nodebb-plugin-spam-be-gone#51]
reCaptcha isn't appearing when a user is registering for a account.

Running NodeBB v1.1.0 (upgraded to v1.1.2 still no captcha)

**Comment by akhoury** [comment]
• do you have it enabled? can you take a screenshot of your settings page, __but remember to hide the sensitive data, basically all the API keys__

• can you open the dev tools and refresh the page to see if there are any errors and take a screenshot for those?

**Comment by barisusakli** [comment]
Let us know if this is still happening on latest
