### ISSUE TITLE
Send more data to Akismet

### ISSUE THREAD

**Issue by cfinke** [akhoury/nodebb-plugin-spam-be-gone#54]
Currently, calls to Akismet only include `user_ip`, `user_agent`, `permalink`, `comment_content`, and `comment_author`.  Ideally, they should also include `referrer`, `comment_type`, and `comment_author_email`.

`comment_author_email` is probably the most important one. A blank `comment_type` is assumed to be `"comment"`, but it should probably be `"forum-post"` for new threads and `"comment"` for replies to threads.

Chris Finke
Akismet

**Comment by akhoury** [comment]
sounds fair

**Comment by akhoury** [comment]
according to this: https://blog.akismet.com/2012/06/19/pro-tip-tell-us-your-comment_type/

> forum-post
> Forum posts and replies.

which mean both topics and posts should be send as `forum-post`

**Comment by akhoury** [comment]
Also, since when `blog` is required? https://akismet.com/development/api/#comment-check

**Comment by cfinke** [comment]
> both topics and posts should be send as forum-post

That post predates some work I've done on differentiating new forum posts from replies to posts, and the advice in it is still ok, but sending `comment` for post replies is now marginally more effective. I'll update the post.

**Comment by akhoury** [comment]
got it, thanks!

**Comment by barisusakli** [comment]
Seems like `referrer, comment_type, and comment_author_email` are added
