### ISSUE TITLE
Admin unable to edit users post

### ISSUE THREAD

**Issue by joolswills** [akhoury/nodebb-plugin-spam-be-gone#56]
NodeBB - 1.4.3
nodebb-plugin-spam-be-gone - 0.4.10

I was edited a users post, and on submission it was being flagged as spam. The user was under the threshold, but as an Admin it should be possible to bypass the spam check if editing a users post.

Also - is 0.4.11 going to be made available via npm or is it waiting on a fix ?

Thanks for your time.

**Comment by barisusakli** [comment]
I think this is fixed admins arent flagged as spam now.
