### ISSUE TITLE
using a deprecated hook

### ISSUE THREAD

**Issue by tehspaceg** [akhoury/nodebb-plugin-spam-be-gone#58]
After upgrading to NodeBB 1.5, I am seeing the following warning in my logs:
```8/5 14:13:56 [18121] - warn: [plugins/nodebb-plugin-spam-be-gone] Hook `action:post.flag` is deprecated, please use `action:flag.create` instead.```

**Comment by barisusakli** [comment]
Use 0.5.0 of this plugin
https://github.com/akhoury/nodebb-plugin-spam-be-gone/commit/484a0b76c5d253802619ca96a3c5e83579c79f84
