### ISSUE TITLE
Use recaptcha.net to replace google.com/recaptcha

### ISSUE THREAD

**Issue by Ghost-chu** [akhoury/nodebb-plugin-spam-be-gone#68]
all we know, google was blocked in china, and recaptcha can't use too.

so just replace to google offical mirror `recaptcha.net` and it will work in global everywhere.

**Comment by akhoury** [comment]
oh, sure thing, for second there, I thought `recaptcha.net` is just a proxy, but looks like it's official

https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally
