### ISSUE TITLE
Plugin v.0.7.0 not working

### ISSUE THREAD

**Issue by Per0x** [akhoury/nodebb-plugin-spam-be-gone#73]
The latest version 0.7.0 is not working with my latest NodeBB 1.13.3
Spam-be-gone is showing in admin settings after a rebuild, but I can't save any modifications. There is no response and google recaptcha is not working for new users either.

**Comment by julianlam** [comment]
Might be an issue with my PR, I'll take a look, sorry about that!

**Comment by julianlam** [comment]
#72 :point_left:

**Comment by Per0x** [comment]
Thanks, but I solved it by simply doing a rollback in the meantime.
npm i nodebb-plugin-spam-be-gone@0.6.7
