### ISSUE TITLE
ReCAPTCHA loading twice

### ISSUE THREAD

**Issue by sandratatarevicova** [akhoury/nodebb-plugin-spam-be-gone#76]
## Summary

ReCAPTCHA is loaded twice when going from login to the register page, which sometimes causes that hCaptcha is loaded instead of reCAPTCHA on the register page.

## Environment

- NodeBB 1.14.3
- nodebb-plugin-spam-be-gone 0.7.2
    - enabled modules: Akismet, Honeypot, Google reCAPTCHA

## Steps to reproduce:

1. Go to `/login`.
2. Click on the `Register` link below the `Login` button.
3. One of the following errors is logged in JS console:
  a) 
    ```
    Uncaught Error: reCAPTCHA has already been rendered in this element
        U recaptcha__en_gb.js:276
        __nodebbSpamBeGoneCreateCaptcha__ scripts.js:121
        i scripts.js:24
    ```
    In this case, everything looks OK from the user's perspective, and reCAPTCHA is correctly rendered in the registration form. This happens for most users.
  b)
    ```
    Uncaught (in promise) Error: reCAPTCHA placeholder element must be empty
        U recaptcha__en_gb.js:277
        __nodebbSpamBeGoneCreateCaptcha__ scripts.js:121
    ```
    In this case, hCaptcha is rendered instead of reCAPTCHA and users are not able to register because hCaptcha is not configured (it is disabled in the administration). This problem was reported by several users. I was able to reproduce it with developer tools with disabled cache, but it does not happen always, so it seems like there is some race condition.

## Relevant links

It might be related to [this change](https://github.com/akhoury/nodebb-plugin-spam-be-gone/commit/5f8ebfaa81df919bb5c34f86eb82cf64d48de461) added within #65.

**Comment by sandratatarevicova** [comment]
As a workaround, we have disabled captcha on the login page (we don't use it anyway) using this patch:

```
--- node_modules/nodebb-plugin-spam-be-gone/public/js/scripts.js
+++ node_modules/nodebb-plugin-spam-be-gone/public/js/scripts.js
@@ -100,9 +100,6 @@
                case 'register':
                        onRegisterPage(data);
                        break;
-               case 'login':
-                       onLoginPage(data);
-                       break;
                case 'account/profile':
                        onAccountProfilePage(data);
                        break;

--- node_modules/nodebb-plugin-spam-be-gone/plugin.json
+++ node_modules/nodebb-plugin-spam-be-gone/plugin.json
@@ -27,9 +27,7 @@
   "hooks": [
     {"hook": "static:app.load", "method": "load"},
     {"hook": "filter:admin.header.build", "method": "admin.menu"},
-    {"hook": "filter:login.build", "method": "addCaptcha", "priority": 5},
     {"hook": "filter:register.build", "method": "addCaptcha", "priority": 5},
-    {"hook": "filter:login.check", "method": "checkLogin", "priority": 5},
     {"hook": "filter:register.check", "method": "checkRegister", "priority": 5},
     {"hook": "filter:user.profileMenu", "method": "userProfileMenu", "priority": 5},
     {"hook": "filter:user.getRegistrationQueue", "method": "getRegistrationQueue", "priority": 5},
```

It seems to work correctly now.

**Comment by barisusakli** [comment]
Can confirm I got this on community with your repro steps.

![image](https://user-images.githubusercontent.com/2583394/99096892-d991b000-25a4-11eb-9deb-47d2dad7697f.png)

**Comment by barisusakli** [comment]
Although I am not sure if you are meant to use both reCaptcha and hCaptcha at the same time. Do you have them both enabled in the ACP?

**Comment by sandratatarevicova** [comment]
> Although I am not sure if you are meant to use both reCaptcha and hCaptcha at the same time. Do you have them both enabled in the ACP?

No, hCaptcha is disabled.

**Comment by barisusakli** [comment]
Can you post the contents of your `config['spam-be-gone']` object after removing the sensitive info? If hCaptcha is disabld it shoulnd't have a `hcaptcha` key I think.

**Comment by barisusakli** [comment]
Also did you have `Enable Re-Captcha on login page as well` in the ACP for recaptcha?

**Comment by sandratatarevicova** [comment]
> Can you post the contents of your config['spam-be-gone'] object after removing the sensitive info?

We don't have this key in `config.json` or did you mean another config?

> Also did you have Enable Re-Captcha on login page as well in the ACP for recaptcha?

No, it was disabled.

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/99101972-65a6d600-25ab-11eb-878f-c413c9bc89fe.png)
Weird maybe the config object isn't created if hcaptcha isn't enabled

**Comment by barisusakli** [comment]
And hcaptcha is only rendered if that config exists https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/master/public/js/register.js#L11

So not sure why you were getting hcaptcha when you have it disabled in the ACP.

**Comment by sandratatarevicova** [comment]
I am not sure if it is relevant, but I was trying to workaround it by configuring hCaptcha (and still keeping it disabled) expecting it would at least work when it was rendered. It did not work, because it was using reCAPTCHA API key for hCaptcha API calls.

When I enabled both reCAPTCHA and hCaptcha, hCaptcha was rendered twice:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/48565887/99104707-a15c9280-25e1-11eb-9608-10be0e05bb74.png">

**Comment by barisusakli** [comment]
I think I found the issue, will require some refactoring to fix though

**Comment by sandratatarevicova** [comment]
It works correctly on 0.7.6. Thank you! 🙂

**Comment by barisusakli** [comment]
@sandratatarevicova please try 0.7.7 when you get a change, there was an issue reported here 

https://community.nodebb.org/topic/15166/empty-captcha-in-login-page-cant-access-admin-settings

https://github.com/akhoury/nodebb-plugin-spam-be-gone/commit/ced3dbde0bc07688d9e3e5a2849c436af0fd97d9

**Comment by sandratatarevicova** [comment]
We don't use captcha on the login page, so I guess this should not affect us, or should we upgrade anyway? 🙂

**Comment by barisusakli** [comment]
It only affects the captcha on login page so if you don't use it no need to upgrade. It will be included in the next release of nodebb.

**Comment by sandratatarevicova** [comment]
OK, thank you 🙂
