### ISSUE TITLE
hCaptcha API.js is downloaded even when hCaptcha is disabled

### ISSUE THREAD

**Issue by UniversalSuperBox** [akhoury/nodebb-plugin-spam-be-gone#78]
spam-be-gone appears to be injecting the hCaptcha API even when it is disabled, in https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/master/library.js#L464-L467.

This means that all of my forum users are loading the hCaptcha API needlessly. Is it possible to disable loading this script when hCaptcha is not enabled?

If the pluginSettings object is available at the point that the script is injected, I think the same check as [library.js#L516-L518](https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/master/library.js#L516-L518) would work. Is pluginSettings available there?

**Comment by barisusakli** [comment]
@UniversalSuperBox let me know if the issue is resovled in 0.7.8

**Comment by UniversalSuperBox** [comment]
Yes, it is fixed. Thank you!
