### ISSUE TITLE
hCaptcha succeeds but NodeBB thinks it fails

### ISSUE THREAD

**Issue by snarlynarwhal** [akhoury/nodebb-plugin-spam-be-gone#82]
Hi, I am using NodeBB v1.17.2 and Spam Be Gone v0.7.9.

This is issue is the same as #74 except for it's the hCaptcha not working on the register page: hCaptcha succeeds, but the same error notification appears. I am using both Google reCAPTCHA. When I disable hCaptcha, the register page works just fine.

**Comment by julianlam** [comment]
@snarlynarwhal Have you tried using just hCaptcha on its own? I am not certain whether you are able to use both at the same time.

**Comment by snarlynarwhal** [comment]
I just tested using hCaptcha on its own and it works. Google reCAPTCHA has not been working well for me -- lots of spam accounts still get generated and make spam posts. Going to give hCaptcha try. Thank you!
