### ISSUE TITLE
StopForumSpam issues.

### ISSUE THREAD

**Issue by tuicemen** [akhoury/nodebb-plugin-spam-be-gone#83]
Currently it appears this addon only allows the option to report spammers.
Many times these user IPs already are in the blacklisted data base.
There should be the option to compare users to the data base prior. Without this we're spamming stopforumspam with unneeded reporting.
Also the option to block user registration based off the database needs to be added as well.
This addon has great potential but currently is missing the mark. The Idea is to stop forum spam not just report it.

**Comment by akhoury** [comment]
hi @tuicemen 

We do check if they're a spammer on registration
https://github.com/akhoury/nodebb-plugin-spam-be-gone/blob/3e36d71e940e0703eb0833aa50aad301c1a7eda5/library.js#L354-L361

and as for the reporting, it is either manual or on the registration queue, but i guess we could add a check if they're already in the database to not to send them.

**Comment by tuicemen** [comment]
Thanks, @akhoury  I see the registration que was disabled here, with it enable it does catch things the check IP prior to reporting would be a nice add though.

**Comment by akhoury** [comment]
@tuicemen I am closing this issue. When we looked StopForumSpam's data, it looks like they keep track of how many time a user has been reported as a spammer using `frequency`, along with the last time seen, using `lastseen`, 
see sample below, along with the link to the stopforumspam repo readme file.

Thank you for reporting though.

```javascript
sfsUser.isSpammer()
	 .then(function (result) {
	    // result is false if not found
	    
	    // if true result looks something like this
	    // result = {
	    //   success: 1,
	    //   username: {
	    //     lastseen: '2015-03-09 15:22:49',
	    //     frequency: 3830,
	    //     appears: 1,
	    //     confidence: 90.2 } }
});

```
https://github.com/deltreey/stopforumspam/blob/84fe90bedf161cd5cb9cef7eb04995b9dc9141a8/README.md?plain=1#L41-L43
