### ISSUE TITLE
is this plugin still alive?

### ISSUE THREAD

**Issue by lslzl3000** [akhoury/nodebb-plugin-spam-be-gone#92]
Cannot work with nodebb v2.2.5
So many issues opening with no response. Is this plugin alive?

**Comment by julianlam** [comment]
Yes, the plugin should work with NodeBB v2. What issues are you seeing?

**Comment by lslzl3000** [comment]
The plugin can be installed and active, I  try to use with google `recaptcha` v2 checkbox
The register/login page will show the check options and can be verified from google

But after click the login button, the login page still shows an error with something like `are u robot?` which seems the verified result did't workout
The register page shows no error, but still unable to process to next page.

**Comment by lslzl3000** [comment]
![Screen Shot 2022-07-28 at 04 31 19](https://user-images.githubusercontent.com/3398981/181366638-9570e0bb-7ca5-48b0-9775-bc790958da8c.png)
![Screen Shot 2022-07-28 at 04 32 23](https://user-images.githubusercontent.com/3398981/181366643-fef3236b-af4a-47f4-ad2c-5ef7fdecea30.png)

Both button did't workout, nothing shows after click

**Comment by julianlam** [comment]
Could it be related to reCAPTCHA being a google property and inaccessible in China?

What if you set up hCaptcha, does that work?

**Comment by barisusakli** [comment]
https://github.com/akhoury/nodebb-plugin-spam-be-gone/pull/103
try with 2.2.0 maybe that PR fixes your issue
